name: Build Tasks Ayush Edition
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Yahan 17 hata kar 21 likho strictly
          distribution: 'zulu' # Tasks ke liye Zulu distribution kaafi stable hai
          cache: gradle

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build Mobile APK strictly with JDK 21
        # Is baar hum strictly :composeApp module ko compile karenge Java 21 ke saath
        run: ./gradlew :composeApp:assembleDebug --no-daemon

      - name: Upload Correct Tasks APK
        uses: actions/upload-artifact@v4
        with:
          name: Tasks-Mobile-APK
          path: "app/build/outputs/apk/debug/**/*.apk"
          
